spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.uri=db_uri

#aws s3 configuration
aws.access.key=enter_access_key
aws.secret.key=enter_secret_key
aws.region=enter_region
aws.s3.bucketname=enter_db_name

jwt.secret.key=enter_custom_key_32chars

#razorpay configuration
razorpay_key=test_key
razorpay_secret=test_secret